package cn.chandoubatuizi.manage.model;

import java.math.BigDecimal;
import java.util.Date;

public class CountryPriceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.country_code
     *
     * @mbg.generated
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.country_name
     *
     * @mbg.generated
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.currency_unit
     *
     * @mbg.generated
     */
    private String currencyUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.currency_symbol
     *
     * @mbg.generated
     */
    private String currencySymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.tax_rate
     *
     * @mbg.generated
     */
    private BigDecimal taxRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.level_ordinary
     *
     * @mbg.generated
     */
    private Integer levelOrdinary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.level_normal
     *
     * @mbg.generated
     */
    private Integer levelNormal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.level_excellent
     *
     * @mbg.generated
     */
    private Integer levelExcellent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.level_advanced
     *
     * @mbg.generated
     */
    private Integer levelAdvanced;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.level_boutique
     *
     * @mbg.generated
     */
    private Integer levelBoutique;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.charge_type
     *
     * @mbg.generated
     */
    private Byte chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_country_price.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.id
     *
     * @return the value of t_country_price.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.id
     *
     * @param id the value for t_country_price.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.country_code
     *
     * @return the value of t_country_price.country_code
     *
     * @mbg.generated
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.country_code
     *
     * @param countryCode the value for t_country_price.country_code
     *
     * @mbg.generated
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.country_name
     *
     * @return the value of t_country_price.country_name
     *
     * @mbg.generated
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.country_name
     *
     * @param countryName the value for t_country_price.country_name
     *
     * @mbg.generated
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.currency_unit
     *
     * @return the value of t_country_price.currency_unit
     *
     * @mbg.generated
     */
    public String getCurrencyUnit() {
        return currencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.currency_unit
     *
     * @param currencyUnit the value for t_country_price.currency_unit
     *
     * @mbg.generated
     */
    public void setCurrencyUnit(String currencyUnit) {
        this.currencyUnit = currencyUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.currency_symbol
     *
     * @return the value of t_country_price.currency_symbol
     *
     * @mbg.generated
     */
    public String getCurrencySymbol() {
        return currencySymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.currency_symbol
     *
     * @param currencySymbol the value for t_country_price.currency_symbol
     *
     * @mbg.generated
     */
    public void setCurrencySymbol(String currencySymbol) {
        this.currencySymbol = currencySymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.tax_rate
     *
     * @return the value of t_country_price.tax_rate
     *
     * @mbg.generated
     */
    public BigDecimal getTaxRate() {
        return taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.tax_rate
     *
     * @param taxRate the value for t_country_price.tax_rate
     *
     * @mbg.generated
     */
    public void setTaxRate(BigDecimal taxRate) {
        this.taxRate = taxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.level_ordinary
     *
     * @return the value of t_country_price.level_ordinary
     *
     * @mbg.generated
     */
    public Integer getLevelOrdinary() {
        return levelOrdinary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.level_ordinary
     *
     * @param levelOrdinary the value for t_country_price.level_ordinary
     *
     * @mbg.generated
     */
    public void setLevelOrdinary(Integer levelOrdinary) {
        this.levelOrdinary = levelOrdinary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.level_normal
     *
     * @return the value of t_country_price.level_normal
     *
     * @mbg.generated
     */
    public Integer getLevelNormal() {
        return levelNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.level_normal
     *
     * @param levelNormal the value for t_country_price.level_normal
     *
     * @mbg.generated
     */
    public void setLevelNormal(Integer levelNormal) {
        this.levelNormal = levelNormal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.level_excellent
     *
     * @return the value of t_country_price.level_excellent
     *
     * @mbg.generated
     */
    public Integer getLevelExcellent() {
        return levelExcellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.level_excellent
     *
     * @param levelExcellent the value for t_country_price.level_excellent
     *
     * @mbg.generated
     */
    public void setLevelExcellent(Integer levelExcellent) {
        this.levelExcellent = levelExcellent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.level_advanced
     *
     * @return the value of t_country_price.level_advanced
     *
     * @mbg.generated
     */
    public Integer getLevelAdvanced() {
        return levelAdvanced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.level_advanced
     *
     * @param levelAdvanced the value for t_country_price.level_advanced
     *
     * @mbg.generated
     */
    public void setLevelAdvanced(Integer levelAdvanced) {
        this.levelAdvanced = levelAdvanced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.level_boutique
     *
     * @return the value of t_country_price.level_boutique
     *
     * @mbg.generated
     */
    public Integer getLevelBoutique() {
        return levelBoutique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.level_boutique
     *
     * @param levelBoutique the value for t_country_price.level_boutique
     *
     * @mbg.generated
     */
    public void setLevelBoutique(Integer levelBoutique) {
        this.levelBoutique = levelBoutique;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.charge_type
     *
     * @return the value of t_country_price.charge_type
     *
     * @mbg.generated
     */
    public Byte getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.charge_type
     *
     * @param chargeType the value for t_country_price.charge_type
     *
     * @mbg.generated
     */
    public void setChargeType(Byte chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.create_time
     *
     * @return the value of t_country_price.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.create_time
     *
     * @param createTime the value for t_country_price.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_country_price.update_time
     *
     * @return the value of t_country_price.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_country_price.update_time
     *
     * @param updateTime the value for t_country_price.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}