package cn.chandoubatuizi.manage.dao;

import cn.chandoubatuizi.manage.model.CountryPriceDO;

public interface CountryPriceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country_price
     *
     * @mbg.generated
     */
    int insert(CountryPriceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country_price
     *
     * @mbg.generated
     */
    int insertSelective(CountryPriceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country_price
     *
     * @mbg.generated
     */
    CountryPriceDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CountryPriceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_country_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CountryPriceDO record);
}